### ISSUE TITLE
gdcRNADownload error with GDC-client

### ISSUE THREAD

**Issue by IL2liu** [Jialab-UCR/GDCRNATools#11]
When using the follwing code:
####### Download mature miRNA data #######
gdcRNADownload(project.id     = 'TCGA-BRCA', 
               data.type      = 'miRNAs', 
               write.manifest = FALSE,
               method         = 'gdc-client',
               directory      = mirdir)

## we got the following error, that haven't been solved.
ERROR: An unexpected error has occurred during normal operation of the client. Please report the following exception to GDC support <support@nci-gdc.datacommons.io>.
ERROR: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "gdc-client", line 99, in <module>
  File "build\bdist.win-amd64\egg\gdc_client\download\parser.py", line 111, in download
  File "build\bdist.win-amd64\egg\gdc_client\download\client.py", line 234, in download_small_groups
  File "build\bdist.win-amd64\egg\gdc_client\download\client.py", line 171, in _download_tarfile
AttributeError: 'NoneType' object has no attribute 'status_code'
ERROR: Exiting
Traceback (most recent call last):
  File "logging\__init__.py", line 861, in emit
  File "logging\__init__.py", line 734, in format
  File "build\bdist.win-amd64\egg\gdc_client\log\log.py", line 36, in format
  File "logging\__init__.py", line 465, in format
  File "logging\__init__.py", line 325, in getMessage
TypeError: __str__ returned non-string (type SysCallError)
Logged from file client.py, line 150

**Comment by IL2liu** [comment]
Following the suggestion of Dr. Li, This problem was solved by using update R to 3.6.1 .

Thank you for your help.

**Comment by mahsa-moony** [comment]
Hi.
I have this problem too. I updated my r to the latest version(4.0.0) but I still get this error. I would appreciate it if someone can help me.

**Comment by BioLiu** [comment]
> Hi.
> I have this problem too. I updated my r to the latest version(4.0.0) but I still get this error. I would appreciate it if someone could help me.

Hi.
I got the same problem. I found gdc-client has different packages for different Python version, you can check it in [their web site](https://gdc.cancer.gov/access-data/gdc-data-transfer-tool). I checked code of gdcRNADownload.R and didn't found related test the version of Python; it downloads the gdc-client for Python 2.7.  I solved the problem by downloading the gdc-client according to the version of Python of my platform, since my version is Python 3, I downloaded  gdc-client_v1.5.0 and solved the problem. 
Best wishes!

**Comment by romylland** [comment]
> 
> 
> Hi.
> I have this problem too. I updated my r to the latest version(4.0.0) but I still get this error. I would appreciate it if someone could help me.

Hi @mahsa-moony were you able to fix your problem? I was in the same situation as you but following @BioLiu's suggestion it solved it.
